export enum Type {
  CREDIT = "CREDIT",
  WITHDRAWAL = "WITHDRAWAL",
}

export enum Status{
    ACTIVE="ACTIVE",
    INACTIVE="INACTIVE"
}

export enum WITHDRAWAL_STATUS{
    PENDING='PENDING',
    APPROVED='APPROVED',
    REJECTED='REJECTED',
}